### ISSUE TITLE
TensorFlow 1.0 compatibility

### ISSUE THREAD

**Issue by nengine** [JoelKronander/TensorFlask#1]
Hi, Please let me know this would work with TF 1.0?  I am getting errors below with run with TF 1.0.

```
Traceback (most recent call last):
  File "train_model.py", line 111, in <module>
    train_model()
  File "train_model.py", line 41, in train_model
    ce = tf.reduce_mean(tf.nn.sparse_softmax_cross_entropy_with_logits(y, y_))
  File "C:\Users\nash\Anaconda2\envs\py35\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 1684, in sparse_softmax_cross_entropy_with_logits
    labels, logits)
  File "C:\Users\nash\Anaconda2\envs\py35\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 1533, in _ensure_xent_args
    "named arguments (labels=..., logits=..., ...)" % name)
ValueError: Only call `sparse_softmax_cross_entropy_with_logits` with named arguments (labels=..., logits=..., ...)
```

**Comment by JoelKronander** [comment]
Hi, just pushed a commit to fix this.
Thanks for the post.

**Comment by nengine** [comment]
Thanks a lot.
